# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-07 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=250)),
                ('priceBought', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.CharField(max_length=250)),
                ('bookmarkPrice', models.CharField(max_length=250)),
                ('setDate', models.CharField(max_length=250)),
                ('bookmarkAmount', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.CharField(max_length=250)),
                ('cryptoPrice', models.CharField(max_length=250)),
                ('cryptoTime', models.CharField(max_length=250)),
                ('cryptoAmount', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.CharField(max_length=250)),
                ('stockPrice', models.CharField(max_length=250)),
                ('stockTime', models.CharField(max_length=250)),
                ('stockAmount', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
    ]
